config {
  type: "incremental",
  schema: "staging",
  description: "Silver layer: cleaned sales events enriched with product cost"
}

SELECT
  s.event_id,
  s.shipment_id,
  s.branch,
  s.product_id,
  s.customer_id,
  s.color,
  s.size AS sizeproduct,
  s.quantity,
  s.price,
  s.quantity * s.price AS total_price,
  s.quantity* p.cost_price AS total_cost, 
  s.currency,
  s.payment_method,
  FORMAT_TIMESTAMP("%Y-%m-%d %H:%M", s.timestamp, "Europe/Istanbul") AS sales_zaman
FROM ${ref({schema:"landingzone", name:"pubsub_events"})} s
LEFT JOIN ${ref({schema:"staging", name:"stg_clothing_db_products"})} p
  ON s.product_id = p.product_id
WHERE s.returned_sale_id IS NULL
