config {
  type: "incremental",
  schema: "staging"
}


SELECT
  event_id,
  shipment_id,
  branch,
  product_id,
  customer_id,
  color,
  size,
  quantity,
  price,
  quantity*price as total_price,
  currency,
  payment_method,
  returned_sale_id,
  FORMAT_TIMESTAMP("%Y-%m-%d %H:%M", shipment_date, "Europe/Istanbul") as return_zaman
FROM ${ref({schema:"landingzone" ,name:"pubsub_events"})}
WHERE returned_sale_id IS NOT NULL
