config {
  type: "table",
  schema: "core"
}
SELECT
  b.branch_id,
  COUNT(*) AS total_sales_count,
  SUM(s.quantity) AS total_quantity_sold,
  ROUND(SUM(s.quantity * s.price), 2) AS total_revenue,
  ROUND(SUM(s.total_cost),2) AS all_total_cost,
FROM ${ref({schema:"staging" ,name:"stg_pubsub_sales"})} as s
JOIN ${ref({schema:"landingzone" ,name:"branches"})} as b
ON s.branch = b.branch_id
GROUP BY b.branch_id
ORDER BY total_revenue DESC