config {
  type: "table",
  schema: "core",
  name: "customer_total_spend"
}

SELECT
  c.customer_id,
  c.first_name,
  c.last_name,
  c.country,
  SUM(s.quantity) AS total_quantity_bought,
  ROUND(SUM(s.total_price), 2) AS total_spend
FROM ${ref({schema:"staging", name:"stg_pubsub_sales"})} s
JOIN ${ref({schema:"staging", name:"stg_clothing_db_customers"})} c
  ON s.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name,c.country
ORDER BY total_spend DESC
