config {
    type: "table",
    schema: "core",
    description: "Total sales per category per branch"
}

SELECT
    s.branch AS branch_id,
    p.category,
    COUNT(*) AS total_sales_count,
    SUM(s.quantity) AS total_quantity_sold,
    ROUND(SUM(s.quantity * s.price), 2) AS total_revenue,
    ROUND(SUM(s.quantity * p.cost_price), 2) AS total_cost,
    ROUND(SUM((s.price - p.cost_price) * s.quantity), 2) AS total_profit,
    s.currency,
FROM ${ref({schema:"staging", name:"stg_pubsub_sales"})} s
LEFT JOIN ${ref({schema:"staging", name:"stg_clothing_db_products"})} p
    ON s.product_id = p.product_id
GROUP BY s.branch, p.category, s.currency
ORDER BY s.branch, total_revenue DESC
