config {
  type: "table",           
  schema: "core"
}

SELECT
    r.branch_id,
    r.product_id,
    s.supplier_name,
    SUM(r.quantity) AS total_quantity,
    MAX(r.movement_date) AS last_restock_date
FROM ${ref({schema:"staging", name:"stg_clothing_db_restock_movements"})} AS r
JOIN ${ref({schema:"staging", name:"stg_dim_suppliers"})} AS s
  ON r.supplier_id = s.supplier_id
GROUP BY
    r.branch_id,
    r.product_id,
    s.supplier_name
